package com.moroneyr.compt;

/**
 * Created by MoroneyR on 30/08/2017.
 */

public class QuestionLibrary {

    private String mQuestions [] = {
            "A computer technician is responding to a call about a printer that is causing streaks to appear on every printout. Which of the following is the MOST likely cause?",
            "A technician has connected a laptop to a television via HDMI cable. The entire display cannot be seen on the television. Which of the following settings should the technician modify?",
            "A small workgroup inherits a second-hand printer without networking capabilities. Which of the following is the BEST method of sharing this resource among the workgroup?",
            "Which of the following display technologies provides the BEST range of visible colors?",
            "Which of the following adapters converts an analog signal to a digital signal?",
            "Under normal circumstances, which of the following wireless standards provides the slowest transfer speed at 2.4GHz?",
            "A technician connects a second monitor to a desktop. It is physically located to the right of the existing monitor, but the mouse pointer can only get to the second monitor by moving to the left edge of the screen of the first monitor. Which of following display settings needs to be adjusted to get the pointer to move with the physical placement of the monitor?",
            "A technician upgrades an older computer to Windows 8. The computer is running unusually slow, but the hardware has no problems and is adequate for the OS. Which of the following is the MOST likely solution?",
            "For which of the following types of printers should a technician obtain a maintenance kit containing a fuser, transfer roller, and pickup rollers?",
            "A technician is building a new PC and notices that it has 8 DIMM sockets labeled 0 through to 8. Four are white and four are blue. Which of the following should the technician do FIRST?",
            "A technician needs to run a diagnostic DVD on a laptop running Windows 8.1. After setting the boot order in the UEFI BIOS to the internal DVD-RW drive, the laptop still boots into Windows. Which of the following settings needs to be adjusted in order for the laptop to boot from the DVD-RW drive?",
            "A user is searching for a piano keyboard to connect to a PC. The user would like the keyboard to communicate with the PC. Which of the following features should the user look for on a piano keyboard to BEST facilitate this?",
            "Which of the following cable connection types is an example of a mini DIN?",
            "Which of the following protocols would be used for file sharing between MAC OS and Windows OS workstations on a LAN?",
            "A technician is installing Hyper-V and is getting an error that the software is not able to be installed. Which of the following processor characteristics should be checked?",
            "A technician is troubleshooting an expansion card in a computer that allows the computer to receive faxes over a VoIP line. The line connected to the expansion card is MOST likely which of the following cable types?",
            "Which of the following RAM types can continue working if there is corrupt data?",
            "A user wants to reduce the amount of paper consumed on a multi-function printer. Which of the following settings should be configured to achieve this outcome?",
            "An IT Director wants to increase security on the company website to prevent man-in-the- middle attacks. Which of the following Internet protocols should be implemented to meet the requirement?",
            "Which of the following MUST be the same when replacing a hard drive in a laptop?",
            "Which of the following Internet connection types is known to have a significantly higher latency than the others?",
            "Which of the following is required during the installation of a digitizer?",
            "A small company needs to print several color copies of the same contract to go to various departments and customers. Which of the following printers will be the QUICKEST?",
            "Which of the following is important when replacing a power supply in a workstation located in a datacenter server rack?",
            "The technician would like to upgrade a workstation by adding a USB 3.0 card, and upgrading the video card, sound card, and NIC. The technician is concerned about power consumption by the expansion cards. Which of the following upgrades would MOST likely require also upgrading the power supply?",
           //28.A user wants to extend a PC’s capacity by connecting external devices. Which of the following connectors will allow the user to accomplish this? (Select TWO).
            "A customer wants a computer for performing a single-threaded task as quickly as possible. Which of the following CPU characteristics is the MOST important?",
            //30. Which of the following types of cables are MOST likely to be used to connect to an external hard drive? (Select TWO).
            "A technician replaces a defective 250GB hard drive in a desktop with a 2TB hard drive. After installation, the computer detects the new 2TB drive as a 250GB drive. Which of the following should the technician do to fix this issue?",
            "Which of the following types of expansion slots is MOST frequently found in blade servers?",
            "Which of the following devices does a technician need to calibrate as part of an installation?",
            "A customer wants to transfer data from the DVR to a DVD. Which of the following should be used on a workstation in order to extract the data for archiving?",
            "A technician is building a workstation that is to be used as an HTPC and will sit next to the audio receiver. Which of the following form factors would the technician MOST likely use because of its size?",
            "Which of the following memory types is primarily used in laptops?",
            "Which of the following BEST describes the reason a network administrator would task a technician with replacing a hub with a switch?",
            "A network administrator has a requirement to implement a Wi-Fi hot-spot for the public. Which of the following should be used for secure access?",
            "Which of the following Internet connection types is a digital form that runs over standard telephone wiring?",
            "There are 20 laptops in a room and they all need to connect wirelessly to the network. Which of the following would be the BEST device to use?",
            //Start of topic 2/Networking
            "Which of the following is an advantage of using DHCP for network addressing?",
            "A user wants to implement a wireless router that will have the fastest data speeds and operate over the 5GHz frequency. Which of the following standards should the user select?",
            "A technician is tasked with replacing all the APs in an office building for greater speeds. The current location of APs allowed for total coverage of WiFi throughout the office. Which of the following 802.11 standards should be used?",
            "Which of the following connectors are commonly used for fiber optic cables?",
            "Which of the following devices is BEST to use when designing a SOHO network to ensure the least amount of collisions?",
            "Joe, a technician, is tasked to install a new client machine. He notices the machine is not getting any network connectivity. He tests the network cable between the PC and the network jack and confirms it is good. Joe goes to the network closet and finds several network cables not connected to the switch. Which of the following tools would Joe use to determine which cable goes back to the correct network jack?",
            "The device that allows two different networks to communicate with one another is:",
            "A technician is connecting a PoE enabled phone and needs to run the drop from the switch that is 55 meters (180.4 feet) away. Which of the following cable types would be the MOST suitable for this purpose?",
            "A technician needs to run a cable for a new computer and the requirement is CAT6. Which of the following wiring connectors should the technician use when terminating the cable?",
            //Question 50 Below
            "Which of the following ports is typically used for sending email?",
            "Which of the following ports is used for a secure browser connection for an online purchase?",
            "Which of the following is a public IP address?",
            "A machine receives an IP address starting with 169.254.x.x when which of the following occurs?",
            "A technician is tasked with finding and labeling where a network connection terminates in a patch panel. Which of the following tools would be BEST for the technician to use?",
            //Topic 3 Mobile Devices
            "A customer asks a technician for a device that has the capability to easily connect a laptop to an external monitor, keyboard, mouse, and charge the battery. Which of the following devices should the technician recommend to the customer?",
            "A user wants to quickly share pictures between mobile devices. The devices will be in close proximity so the necessity of a third party service and/or another networking device is not required. Which of the following is the BEST option for this scenario?",
            "Android smartphones are typically different from other smartphone devices in that:",
            "A customer wants the thinnest laptop possible. Which of the following display technologies typically allows for thinner devices?",
            "A user is requesting a cable to charge and transfer data for an Apple mobile device. Which of the following connection types would satisfy the user's requirements?",
            "A customer brings a laptop in for repair, because the screen image is upside down. Which of the following is the BEST solution?",
            "A technician is working on a laptop with a failed Ethernet port caused by ESD. Which of the following is the simplest solution to restore network connectivity?",
            "A laptop logon screen can barely be seen, despite adjusting the display’s brightness setting. Which of the following display components is defective?",
            "Wearable fitness tracking devices use which of the following technologies to determine user activity levels?",
            "When a technician is planning to replace a laptop hard drive, the technician will need to:",
            "A user reports that the cursor jumps to random screen locations when typing on a laptop computer. Which of the following devices is MOST likely causing this?",
            "A customer struggles with the small print of most smartphones. The customer still likes the idea of using a smartphone for phone calls and work. Which of the following devices should the technician recommend to the customer?",
            "Recently a company updated their network infrastructure. A user reports that a laptop is experiencing slower network speeds since the update. Which of the following would the technician replace, rather than purchase a new device?",
            "Which of the following components is responsible for converting light into digital information?",
            "Which of the following would need to be enabled on a mobile phone to share its Internet connection with multiple devices simultaneously?",
            "A laptop is setup at a podium for a presentation but is set to extended desktop. The presenter would like it to show exactly what the laptop screen is showing. Which of the following would be the QUICKEST way to accomplish this?",
            "A laptop has a network port that is not working consistently and wireless is out of range. Which of the following would the technician do to quickly get the laptop back on the wired network?",
            "A user has downloaded an image file and needs to install an application from the image. When trying to execute or open the file, an error is displayed. Which of the following should the user perform?",
            "A user, Ann, is preparing to travel abroad and wants to ensure that her laptop will work properly. Which of the following components of the laptop should be verified FIRST to ensure power compatibility before traveling?",
            "Legacy software needs to be installed on a netbook. Which of the following is MOST likely needed in order to install the software?",
            "A user has requested a device that could be used for web-conferences while away from work. The device will mainly be used for emailing, document reviewing, and phone calls. Which of the following mobile devices would a technician MOST likely recommend?",
            "When the technician plugs the Ethernet cable for the phone into the wall port, the phone fails to turn on. When the technician plugs the Ethernet cable directly into the computer, the computer is able to access the network. Which of the following is the MOST likely cause of this issue?",
            "Ann, a user, reports her docked mobile workstation will periodically lose her network share drive and lose video to the second monitor. Which of the following is MOST likely the cause of this anomaly?",
            "A technician receives a call that a client’s PC is not booting after a recent test of the building’s back-up generators. When the technician arrives, it is discovered that, once powered on, there is no output display or POST beep codes. Furthermore, after 15 seconds, the system’s fans begin running much louder and faster. Which of the following is the MOST likely issue?",
            "A user is trying to use an external hard drive with an incompatible file system. Which of the following tools will allow the user to change the file system on the hard drive?",
            "An office printer that was working earlier in the day is no longer printing any documents. Pre-existing workstations are manually configured to print to the printer directly over the network. A technician has started to troubleshoot the problem and determines that the printer can still be seen in the network directory. The technician has also verified that the printer can print self-diagnostic pages successfully. Which of the following is the MOST likely cause of the problem?",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",


    };


    private String mChoices [] [] = {
            {"Duplex unit", "Toner cartridge", "Imaging Drum", "Pickup rollers"},
            {"Keystone", "Resolution", "Privacy filter", "Frame rate"},
            {"Connect the printer to a Bluetooth adapter in order for the users to print", "Connect the printer by using the onboard Infrared port", "Connect the printer to a user’s workstation and share the device", "Connect the printer to a parallel switch box"},
            {"CRT", "LCD", "Plasma", "OLED"},
            {"S-Video to RCA", "HDMI to VGA", "VGA to DVI-D", "DVI-D to HDMI" },
            {"802.11a", "802.11b", "802.11g", "802.11n"},
            {"Scaling", "Rotation", "Position", "Resolution",},
            {"Change the boot sequence", "Switch the BIOS to UEFI", "Defragment the hard drive", "Enable virtualization"},
            {"Thermal", "Impact", "Inkjet", "Laser"},
            {"Install the memory in the four white slots", "Install the memory in the four blue slots", "Consult the motherboard documentation", "Install the memory in slots 0 through 3", "Fill all slots with memory"},
            {"TPM", "Virtualization", "Secure Boot", "UEFI BIOS password"},
            {"MIDI", "USB", "TCP", "HDMI",},
            {"BNC", "PS/2", "RCA", "DB9"},
            {"IMAP", "SMB", "SSH", "RDP"},
            {"Cache size", "Virtualization support", "Number of cores", "Hyperthreading"},
            {"Coaxil", "CAT3", "CAT6", "Multi-mode fiber", "Single-mode fiber"},
            {"Non-parity", "Dual channel", "Buffered", "ECC"},
            {"Orientation", "Duplex", "Collate", "Economy ink"},
            {"HTTPS", "IMAP", "TELENET", "SMTP"},
            {"The interface type of the existing drive", "The speed of the new drive", "The total data capacity of the PC", "The cache size of the new drive"},
            {"Cable", "Satellite", "DSL", "Fiber"},
            {"Must be connected to the Internet", "Must be cleaned", "Must have the latest software installed", "Must be calibrated"},
            {"3D printing", "Thermal printing", "Impact printing", "Laser printing"},
            {"A fanless power supply should be used", "The proper voltage must be selected", "The unit must be the same or less wattage", "The power connector location must be the same"},
            {"Video card", "USB 3.0 card", "Sound card", "Network card"},
            {"Clock speed", "Hyperthreading", "Fan speed", "Number of cores"},
            {"Reinstall the drive", "Patch the OS", "Upgrade the driver", "Flash the BIOS"},
            {"PCIe", "PCI", "PCI-X", "miniPCI"},
            {"Mouse", "Touch screen", "Keyboard", "Video card"},
            {"Optical drive", "Capture card", "Thunderbolt", "External storage"},
            {"ATX", "Mini-ITX", "AT", "Micro-ATX"},
            {"SDRAM", "DDR2", "ECC", "SODIMM"},
            {"The hub did not provide PoE", "The hub had too many collisions", "The hub was out of ports", "The hub had a bad port"},
            {"WEP and TKIP", "WPA2 and AES", "WPA and static IPs", "WPA2 and MAC filtering"},
            {"Fiber", "Dial-up", "Cable", "DSL"},
            {"Switch", "Router", "Access point", "Hub"},
            {"Simplified configuration", "More addresses are available", "Faster connection speeds", "Lower latency times"},
            {"802.11a", "802.11ac", "802.11g", "802.11n"},
            {"a", "ac", "b", "g", "n"},
            {"RJ-11 and RJ-45", "ST and LC", "F-connectors", "BNC"},
            {"Swtich", "Bridge", "Hub", "Access point"},
            {"Loopback plug", "Toner probe", "WiFi analyzer", "Punchdown tool"},
            {"a repeater", "a hub", "a router", "an access point"},
            {"Fiber", "Coaxil", "CAT3", "CAT6"},
            {"BNC", "RJ-12", "RJ-45", "ST"},
            {"21", "22", "23", "25"},
            {"23", "80", "110", "443"},
            {"10.45.xxx.xxx", "169.254.xxx.xxx", " 173.16.xxx.xxx", "192.168.xxx.xxx"},
            {"When the machine is using IPv6", "When the next IP range begins with 169.253", "When the DHCP server does not respond", "When the operating system is UNIX or LINUX"},
            {"Ethernet cable tester", "Tone generator and probe", "RJ-45 loopback plug", "Patch panel and punchdown tool"},
            {"Lightning", "KVM switch", "USB 3.0", "Docking station"},
            {"NFC", "USB", "IR", "WiFi"},
            {"Android devices use apps that are more secure than other devices.", "Android devices use open source operating systems.", "Android devices can only operate with a proprietary operating system.", "Android devices can receive apps from different sources."},
            {"IPS", "OLED", "LCD", "DisplayPort"},
            {"MicrosUSB", "Molex", "MiniUSB", "Lightning"},
            {"Change the screen orientation", "Replace the video card", "Connect an external monitor", "Update the video card drivers"},
            {"Re-solder the network connector", "Replace the Ethernet daughter board", "Update the Ethernet driver", "Enable wireless and connect to the WAP"},
            {"Backlight", "Digitizer", "Inverter", "Polarizer"},
            {"Digitizer", "Gyroscope", "Accelerometer", "Inverter"},
            {"select a drive that is the correct form factor.", "choose the correct drive cache size for the laptop.", "also upgrade the memory.", "verify voltage requirements."},
            {"The touchpad", "The mouse wheel", "The multimedia keys", "The digitizer"},
            {"A tablet", "An e-Reader", "A phablet", "A smart watch"},
            {"Wireless NIC", "CPU", "RAM", "Hard drive"},
            {"Microfone", "Digitizer", "Inverter", "Webcam"},
            {"NFC", "Bluetooth", "Hotspot", "Tethering"},
            {"Look for the setting in control panel", "Toggle the dual display function key", "Change the screen orientation", "Reboot the laptop"},
            {"Use a USB to RJ-45 dongle", "Enable Bluetooth", "Enable NIC teaming", "Replace the motherboard"},
            {"Download a different file from the website", "Rename the extension of the file to a known extension", "Verify the MD5 hash of the downloaded file", "Mount the file as an emulated DVD"},
            {"Wall adapter", "Battery", "Power supply", "Digitizer"},
            {"Lightning port", "Bluetooth adapter", "USB optical drive", "NFC chip"},
            {"Tablet", "Smart camera", "Phablet", "Web camera"},
            {"The network switch does not support PoE", "The technician is connecting the phone to the wrong type of port", "The firewall on the network is blocking access to the DHCP server", "The Ethernet cable is the wrong type"},
            {"The workstation battery needs to be replaced.", "The NIC is functioning intermittently.", "Failed driver updates for the workstation’s devices.", "The surge protector lost AC power."},
            {"The motherboard was damaged by the power test.", "The PC’s RAM was affected by ESD.", "The power supply was damaged and is nonfunctional.", "The hard drive was erased due to the power test."},
            {"format", "defrag", "bootred", "chkdsk"},
            {"The printer's IP address has changed.", "The network print spooler service has been restarted.", "Perform Printer Maintenance message is displayed on the printer’s LCD panel.", "Two or more users sent print jobs simultaneously, causing a print collision"},
            {"", "", "", ""},
            {"", "", "", ""},
            {"", "", "", ""},
            {"", "", "", ""},
            {"", "", "", ""},
            {"", "", "", ""},
            {"", "", "", ""},
            {"", "", "", ""},
            {"", "", "", ""},
            {"", "", "", ""},
            {"", "", "", ""},
            {"", "", "", ""},
            {"", "", "", ""},
            {"", "", "", ""},
            {"", "", "", ""},
            {"", "", "", ""},
            {"", "", "", ""},
            {"", "", "", ""},
            {"", "", "", ""},
            {"", "", "", ""},
            {"", "", "", ""},
            {"", "", "", ""},
            {"", "", "", ""},
            {"", "", "", ""},
            {"", "", "", ""},
            {"", "", "", ""},
            {"", "", "", ""},
            {"", "", "", ""},
            {"", "", "", ""},
            {"", "", "", ""},
            {"", "", "", ""},
            {"", "", "", ""},
            {"", "", "", ""},
            {"", "", "", ""},
            {"", "", "", ""},
            {"", "", "", ""},
            {"", "", "", ""},
            {"", "", "", ""},
            {"", "", "", ""},
            {"", "", "", ""},
            {"", "", "", ""},
            {"", "", "", ""},
            {"", "", "", ""},
            {"", "", "", ""},
            {"", "", "", ""},
            {"", "", "", ""},
            {"", "", "", ""},
            {"", "", "", ""},
            {"", "", "", ""},
            {"", "", "", ""},
            {"", "", "", ""},
            {"", "", "", ""},
            {"", "", "", ""},
            {"", "", "", ""},
            {"", "", "", ""},
            {"", "", "", ""},
            {"", "", "", ""},
            {"", "", "", ""},
            {"", "", "", ""},
            {"", "", "", ""},
            {"", "", "", ""},
            {"", "", "", ""},
            {"", "", "", ""},
            {"", "", "", ""},
            {"", "", "", ""},
            {"", "", "", ""},
            {"", "", "", ""},
            {"", "", "", ""},
            {"", "", "", ""},
            {"", "", "", ""},
            {"", "", "", ""},
            {"", "", "", ""},
            {"", "", "", ""},
            {"", "", "", ""},
            {"", "", "", ""},
            {"", "", "", ""},
            {"", "", "", ""},
            {"", "", "", ""},
            {"", "", "", ""},
            {"", "", "", ""},
            {"", "", "", ""},
            {"", "", "", ""},
            {"", "", "", ""},
            {"", "", "", ""},
            {"", "", "", ""},
            {"", "", "", ""},
            {"", "", "", ""},
            {"", "", "", ""},
            {"", "", "", ""},
            {"", "", "", ""},
            {"", "", "", ""},
            {"", "", "", ""},
            {"", "", "", ""},
            {"", "", "", ""},
            {"", "", "", ""},
            {"", "", "", ""},
            {"", "", "", ""},
            {"", "", "", ""},
            {"", "", "", ""},
            {"", "", "", ""},
            {"", "", "", ""},
            {"", "", "", ""},
            {"", "", "", ""},
            {"", "", "", ""},
            {"", "", "", ""},
            {"", "", "", ""},
            {"", "", "", ""},
            {"", "", "", ""},
            {"", "", "", ""},







    };

    private String mCorrectAnswers[] = {"Imaging Drum",
            "Resolution",
            "Connect the printer to a user’s workstation and share the device",
            "OLED",
            "VGA to DVI-D",
            "802.11b",
            "Position",
            "Defragment the hard drive",
            "Laser",
            "Consult the motherboard documentation",
            "Secure Boot",
            "MIDI",
            "PS/2",
            "SMB",
            "Virtualization support",
            "Multi-mode fiber",
            "ECC",
            "Duplex",
            "HTTPS",
            "The interface type of the existing drive",
            "Satellite",
            "Must be calibrated",
            "Laser printing",
            "The proper voltage must be selected",
            "Video card",
            "Clock speed",
            "Flash the BIOS",
            "PCI-X",
            "Touch screen",
            "Capture card",
            "Mini-ITX",
            "SODIMM",
            "The hub had too many collisions",
            "WPA2 and AES",
            "DSL",
            "Simplified configuration",
            "802.11ac",
            "ac",
            "ST and LC",
            "Switch",
            "Toner probe",
            "a router",
            "CAT6",
            "RJ-45",
            "25",
            "443",
            "173.16.xxx.xxx",
            "When the DHCP server does not respond",
            "Tone generator and probe",
            "Docking station",
            "NFC",
            "Android devices use open source operating systems.",
            "OLED",
            "Lightning",
            "Change the screen orientation",
            "Enable wireless and connect to the WAP",
            "Backlight",
            "Accelerometer",
            "select a drive that is the correct form factor.",
            "The touchpad",
            "A phablet",
            "Wireless NIC",
            "Webcam",
            "Hotspot",
            "Toggle the dual display function key",
            "Use a USB to RJ-45 dongle",
            "Mount the file as an emulated DVD",
            "Wall adapter",
            "USB optical drive",
            "Phablet",
            "The network switch does not support PoE",
            "The surge protector lost AC power.",
            "The motherboard was damaged by the power test.",
            "format",
            "The printer's IP address has changed.",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",


    };

    public String getQuestion(int a) {
        String question = mQuestions[a];
        return question;
    }

    public String getChoice1(int a) {
        String choice0 = mChoices[a][0];
        return choice0;
    }

    public String getChoice2(int a){
        String choice1 = mChoices[a][1];
        return choice1;
    }

    public String getChoice3(int a){
        String choice2 = mChoices[a][2];
        return choice2;
    }
    public String getChoice4(int a){
        String choice3 = mChoices[a][3];
        return choice3;
    }

    public String getCorrectAnswer(int a){
        String answer = mCorrectAnswers[a];
        return answer;
    }
}
